#!/bin/sh
#********************************************************************************
# Copyright (c) 2018, 2023 OFFIS e.V.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0.
#
# SPDX-License-Identifier: EPL-2.0
# 
# Contributors:
#    Jörg Walter - initial implementation
# *******************************************************************************/
file="${0##*[/\\]}"
dir="${0%"$file"}"
dir="${dir:-.}"
cd "$dir/.."
dir="$PWD"
cd - >/dev/null
export PATH="$dir/bin"
export LD_LIBRARY_PATH="$dir/lib"
export CCACHE_CONFIGPATH="$dir/etc/ccache.conf"
export CCACHE_DIR="$dir/.cache/ccache"
export SHELL="$dir/bin/sh"
unset PYTHONHOME PYTHONPATH MAKEFLAGS
exec "$SHELL" "$dir/etc/cget/cget.sh" "$@"
