#!/bin/sh
dir="$(cd "$(dirname "$0")/.."; pwd)"
export PATH="$dir/bin"
export LD_LIBRARY_PATH="$dir/lib"
export CCACHE_CONFIGPATH="$dir/etc/ccache.conf"
export CCACHE_DIR="$dir/.cache/ccache"
export SHELL="$dir/bin/sh"
unset PYTHONHOME PYTHONPATH MAKEFLAGS
exec "$dir/bin/python" -m pip --isolated "$@"
